### ISSUE TITLE
help me understand

### ISSUE THREAD

**Issue by certainlyWrong** [simotin13/gpcc#1]
Hello, I'm looking for a good function to extract MFCCs on mobile devices. I just need to configure a cmake file to compile a .so file. What do you tell me about your code?

**Comment by simotin13** [comment]
@certainlyWrong 
Hello, I'm afraid you misunderstand this mfcc repository.
I think you are implementing Mel Frequency Cepstral Coefficient, But my mfcc is a C compiler project. So  probably I can't help you.
Regards.

**Comment by certainlyWrong** [comment]
Sorry, I really misunderstood. That's why I decided to ask about the code, as it was different from the implementation pattern.
